name: 'Manual Trigger Test'
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env and GH values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo commit ${{ github.event.inputs.commit }} && echo env.HEAD_COMMIT ${{ env.HEAD_COMMIT }} && echo github.sha ${{ github.sha }} && echo 'master sha is 46c8242'

# I am adding a comment here so I'll have something to commit onto this branch.
# The question is, if I'm in the branch in the in the UI, does it take that sha
# or master's sha?
