name: 'Manual Trigger Test'
on:
  push:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env and GH values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo commit ${{ github.event.inputs.commit }} &&
          echo push.ref ${{ github.event.ref }} &&
          echo push.after ${{ github.event.after }} &&
          echo push.head_commit ${{ github.event.head_commit }} &&
          echo push.commits[0] ${{ github.event.commits[0] }} &&
          echo push.commits[0].id ${{ github.event.commits[0].id }} &&
          echo github.sha ${{ github.sha }} &&
          echo env.HEAD_COMMIT ${{ env.HEAD_COMMIT }}
