name: 'Manual Trigger Test'
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env and GH values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo commit ${{ github.event.inputs.commit }} && echo branch ${{ github.event.inputs.branch }} && echo env.HEAD_COMMIT ${{ env.HEAD_COMMIT }} && echo github.sha ${{ github.sha }}
