name: 'Manual Trigger Test'
on:
  # push:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env and GH values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo commit ${{ github.event.inputs.commit }} &&
          echo push.ref ${{ github.event.ref }} &&
          echo push.after ${{ github.event.after }} &&
          echo push.head_commit ${{ github.event.head_commit }} &&
          echo push.commits[0] ${{ github.event.commits[0] }} &&
          echo push.commits[0].id ${{ github.event.commits[0].id }} &&
          echo github.sha ${{ github.sha }} &&
          echo env.HEAD_COMMIT ${{ env.HEAD_COMMIT }}
      - name: Unconditional Second Step
        run: echo 'I am the second step and I should always run'
      - name: Test Implicit If Truthy Condition
        if: ${{ github.event.inputs.commit }}
        run: echo 'Implicit Boolean registered as true'
      - name: Test Implicit If Falsy Condition
        if: ${{ !github.event.inputs.commit }}
        run: echo 'Not Implicit Boolean registered as true'
      - name: Test Equals Empty String Condition
        if: ${{ github.event.inputs.commit == '' }}
        run: echo 'Equals Empty String registered as true'
      - name: Test Doesn't Equal Empty String Condition
        if: ${{ github.event.inputs.commit != '' }}
        run: echo 'Doesn't Equal Empty String registered as true'
      - name: Test Literal true
        if: ${{ true }}
        run: echo 'Literal true registered as true'
      - name: Unconditional Step After Ifs
        run: echo 'I am a step after all the ifs and I should always run'
