name: 'Manual Trigger Test'
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: false
      branch:
        description: Branch on which to run CI
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.event.inputs.branch }}
  # HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env and GH values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo ${{ env }} && echo ${{ github }}
