name: 'Manual Trigger Test'
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit on which to run CI
        required: true

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit }}
  # HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_print_env:
    name: Print env values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: echo ${{ env }}
