name: 'Read Files into Env'
on:
  push:
env:
  CACHED_DEPENDENCIES_PATH: ${{ github.workspace }}/node_modules

jobs:
  job_install_deps:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        # we use a hash of yarn.lock as our cache key, because if it hasn't changed, our dependencies haven't changed,
        # so no need to reinstall them
      - name: Compute dependency cache key
        id: compute_lockfile_hash
        run: echo "::set-output name=hash::${{ hashFiles('yarn.lock') }}"
      - name: Check dependency cache
        uses: actions/cache@v2
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCIES_PATH }}
          key: ${{ steps.compute_lockfile_hash.outputs.hash }}
      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: yarn install --ignore-engines
    outputs:
      dependency_cache_key: ${{ steps.compute_lockfile_hash.outputs.hash }}
  job_read_files:
    name: Read node_modules Files into Env
    needs: job_install_deps
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Check dependency cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_DEPENDENCIES_PATH }}
          key: ${{ needs.job_install_deps.outputs.dependency_cache_key }}
      - name: Read Files
        id: read_files
      # - name: Put Files in Env
        # run: echo "FILENAMES=$(yarn ts-node readFiles.ts)" >> $GITHUB_ENV
        run: echo "::set-output name=filenames::${{ $(yarn ts-node readFiles.ts) }}"
      - name: Print files
        run: echo ${{ steps.read_files.outputs.filenames }}
    outputs:
      file_list: ${{ steps.read_files.outputs.filenames }}
  job_print_files:
    name: Print node_modules Files
    needs: [job_install_deps, job_read_files]
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Print Files
        run: echo ${{ needs.job_read_files.outputs.file_list }}
