name: 'Get GHA Run Metadata'
on:
  push:
  workflow_dispatch:

jobs:
  job_print_env:
    name: Print env and GH Event values
    runs-on: ubuntu-latest
    steps:
      - name: Do printing
        run: |
          env | sort
          echo "Branch: ${GITHUB_REF_NAME}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit SHA: ${ GITHUB_SHA }"
          echo "Trigger: ${{ github.event_name }}"
          echo
          echo "github ${{ toJSON(github) }}"
