name: 'Get GHA Run Metadata'
on:
  # push:
  workflow_dispatch:

jobs:
  job_print_env:
    name: Print env and GH Event values
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v2
      - name: Do printing
        run: |
          env | sort
          echo "Branch: ${GITHUB_REF_NAME}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit SHA: ${GITHUB_SHA}"
          echo "Commit message: echo $(git log -n 1 --pretty=format:%s ${GITHUB_SHA})"
          echo "Trigger: ${{ github.event_name }}"
          echo
          echo
          echo "github ${{ toJSON(github) }}"
  job_branch_name:
    name: Branch ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ""
  job_metadata:
    name: GHA Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v2
      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s ${GITHUB_SHA})" >> $GITHUB_ENV
      - name: "BRANCH: ${{ github.ref_name }}"
        run: echo ""
      - name: "COMMIT: ${{ env.COMMIT_MESSAGE }}"
        run: echo ""
      - name: "SHA: ${{ github.sha }}"
        run: echo ""
      - name: Read variable
        run: echo "COMMIT_MESSAGE is ${{ env.COMMIT_MESSAGE }}"
      - name: Use in step name - ${{ env.COMMIT_MESSAGE }}
        run: echo ""
